CC = gcc
CFLAGS = -Wall -g
OBJ = main.o event.o participant.o file_handler.o

%.o: %.c
    $(CC) -c -o $@ $< $(CFLAGS)

event_system: $(OBJ)
    $(CC) -o $@ $^ $(CFLAGS)

clean:
    rm -f *.o event_system